vich_uploader:
    db_driver: orm

    mappings:
        suite_images:
             uri_prefix: '%suite_images%'
             upload_destination: '%kernel.project_dir%/public%suite_images%'
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
             delete_on_update: false
             delete_on_remove: false
